spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: amin
    password: root
    url: jdbc:mysql://localhost:3306/aps?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
